### ISSUE TITLE
Morning session: Peer-to-peer code review

### ISSUE THREAD

**Issue by Bondok6** [Reem-lab/To-Do-List#7]
# HI @Reem-lab 

## To Highlight 

- Good Job, Your project is cool  ✅
- There are no technical errors ✅

<img src="https://media2.giphy.com/media/3o72FcJmLzIdYJdmDe/giphy.gif"/>

## Suggestions 

- [ ] I think You should remove all `// eslint-disable-next-line eqeqeq` from your code.

https://github.com/Reem-lab/To-Do-List/blob/13c6057547ca1793fa8b5a891dea45d8e4eecea5/src/index.js#L1

https://github.com/Reem-lab/To-Do-List/blob/13c6057547ca1793fa8b5a891dea45d8e4eecea5/src/index.js#L131

https://github.com/Reem-lab/To-Do-List/blob/13c6057547ca1793fa8b5a891dea45d8e4eecea5/src/index.js#L133

- [ ] I suggest you to add `Getting Started` section to your `README.md` file to make it more clear to the users 
please add `npm install` to install packages and `npm start` to start the server commands.

**Comment by andres-condezo** [comment]
## HI @Reem-lab  !👋
Good job documenting your code!
All the project works perfect :+1: 

## Highlights:
- You have a clean and concise code. 🟢 

![](https://64.media.tumblr.com/5a97be1dba647633e37cce9b571e30d2/tumblr_mnvx967abB1sr1ki0o1_250.gifv) 
...

Congratulations and Happy coding!

**Comment by gabyse1** [comment]
## Hello @Reem-lab
First of all, congratulations on your amazing project that works perfectly. I like the way you use the click event listeners *e.target*, I think it is a good practice.
## Highlights
- Clean and DRY code
- You keep it simple.

No suggestion for now. It looks perfect.
