### ISSUE TITLE
Peer to peer code review 20 Jan

### ISSUE THREAD

**Issue by andres-condezo** [Reem-lab/To-Do-List#8]
## HI @gabyse1 and @Reem-lab 
Good job so far!

## Highlights
- You have a clean code 🟢 
- Nice use of the jsdom plugin!🟢 
![](https://64.media.tumblr.com/5a97be1dba647633e37cce9b571e30d2/tumblr_mnvx967abB1sr1ki0o1_250.gifv) 

Cheers and Happy coding!

**Comment by Bondok6** [comment]
# HI @gabyse1, @Reem-lab 

- Great job 👍
- Awesome to use `Jsdom` 👌
